### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Dokman** [einstein95/crunchy-xml-decoder#76]
When i try to login the login part it give me an error and says me that the login is failed
what i can do?

**Comment by Dokman** [comment]
rrefered to: https://github.com/einstein95/crunchy-xml-decoder/pull/77

**Comment by darkhelmet2016** [comment]
Getting the same error too but even with the fix, had even tried to make a new cookie and it tells me it can not verify my log in and the one copy still have a cookie in all it is downloading is 480p even with the config file set to 720p.

**Comment by Jfigs101** [comment]
same issue here.

**Comment by jsonn** [comment]
They seemed to have moved to a completely different login form, including token for CSRF protection.

**Comment by jsonn** [comment]
I have a working login again, need to sort out a pull request...

**Comment by NizarAloui** [comment]
what do you mean by sorting out the pull request ? thx

**Comment by jsonn** [comment]
Convert my local changes into a form that can be published.

**Comment by NizarAloui** [comment]
Could you expose an example please ?

**Comment by jsonn** [comment]
Please try #78.

**Comment by punisher0** [comment]
Still have same login problem...

**Comment by jsonn** [comment]
Can you check (e.g. by changing the text) which of the two 'Login failed' in login.py you are hitting?

**Comment by punisher0** [comment]
All seems to be ok now except for this anime (http://www.crunchyroll.com/mahou-shoujo-naria-girls)  i can't download french subtilte i'm gettig this error:

Couldn't parse XML file.
Traceback (most recent call last):
  File "C:\Users\punisher\Desktop\CR\crunchy-xml-decoder.py", line 341, in <module>
    makechoise()
  File "C:\Users\punisher\Desktop\CR\crunchy-xml-decoder.py", line 279, in makechoise
    decode.decode(raw_input('Please enter Crunchyroll video URL:\n'))
  File "crunchy-xml-decoder\decode.py", line 126, in decode
    subfile.write(formattedsubs.encode('utf-8-sig'))
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by jsonn** [comment]
Ah, right. subtitle-only mode has another consumer. Should be fixed.

**Comment by Jfigs101** [comment]
How do I download your new version of this project? https://github.com/einstein95/crunchy-xml-decoder/pull/78

**Comment by Jfigs101** [comment]
I may have downnloaded the right version, but it seems like I am getting the error below. Running on windows 10 64bit

Traceback (most recent call last):
  File "C:\Users\jola\Downloads\crunchy-xml-decoder-c519dbb92be6e9cd75f167de3561b3618078c5df\crunchy-xml-decoder-c519dbb92be6e9cd75f167de3561b3618078c5df\crunchy-xml-decoder.py", line 12, in <module>
    import decode
  File "crunchy-xml-decoder\decode.py", line 48
    if len(os.path.join('export', title+'.ass') > 255:
                                                     ^
SyntaxError: invalid syntax

**Comment by jsonn** [comment]
Sorry, typo I didn't trigger due to only using ultimate directly. Should also be fixed now.

**Comment by cwhazzoo** [comment]
I am also having issues logging in. I download the code about 15 minutes ago. I still have the original source code from when this was available on darkztar.com and it still works for logging in. You guys have obviously changed the code quite a bit since then so I dont want to go merging the two.

**Comment by punisher0** [comment]
Its work for login but we have to login everyday so i guess there is a limitation time at cookies ? or what.
and still waiting for subtitle issue to be fixed :)

**Comment by jsonn** [comment]
@punisher0 Just update for that.

**Comment by punisher0** [comment]
I have updated and now got this error when i want to download only subtitle only :
Traceback (most recent call last):
  File "C:\Users\punisher\Desktop\CR\crunchy-xml-decoder.py", line 341, in <module> makechoise()
  File "C:\Users\punisher\Desktop\CR\crunchy-xml-decoder.py", line 279, in makechoise    decode.decode(raw_input('Please enter Crunchyroll video URL:\n'))
  File "crunchy-xml-decoder\decode.py", line 42, in decode
    lang1, lang2, forcesub, forceusa, localizecookies, vquality, onlymainsub = a
ltfuncs.config()
ValueError: need more than 6 values to unpack

**Comment by jsonn** [comment]
That's not a consistent source. You can also just checkout https://github.com/jsonn/crunchy-xml-decoder/tree/unix-hls directly, it's the branch behind the pull request.

**Comment by darkhelmet2016** [comment]
Having the same log in issue where it is showing that have a guest account and having to re log in every day. The website does the same thing now where it forces you to relog in every day or if you close the browser at any time.

**Comment by Dokman** [comment]
you can login if you set it to dimension6

**Comment by Dokman** [comment]
Please tell me anyone if anyone have problems with commit https://github.com/einstein95/crunchy-xml-decoder/commit/d72c2aa7a1f61b28ebc89333c79fb0a27a53b3ad

**Comment by sven212** [comment]
Yeah it results in a login failed. because (at least in the german version and in the version via american vpn) there is no dimension6 with premium, only dimension5 with premium. ![Image of source](https://puu.sh/rkvXV/804a8c888d.png)

If i change it back it works perfectly fine for me.

**Comment by Pikanet128** [comment]
The new login issue has to do with a sessiontoken cookie
That is a session cookie it's self so it gets dumped automatically 
I fixed my auto login myself by just making it a regular cookie that expires next month (same time as the User I'd one does)
Then again loging in every time does not bother my me as I have it setup to do so anyway because it's automatic 
Gets the details From an ini file (so it's not in the code)
Why this is not part of this project I don't get
It's so convenient

**Comment by jsonn** [comment]
Noone has written the logic for just saving & reloading usern ame/password :) I have my own local hacks to just hard-code it in login.py, haven't bothered yet to clean it up.

**Comment by Pikanet128** [comment]
I've hacked my copy a ton
To do what I want 
Well it acually runs similar to Funicom-DL
With a que file so you can paste it a lot of urls 
Start it and walk away 
I really need to clean up Funicom-DL and put it up here
I'm just waiting now for there site update as I know that's going to break it. Then I write it again from scratch and fix the rediculusnes of it. I've learned a lot about python since I wrote it (v2&3) (v1 was batch script to call rtmpdump back when they still used rtmp)
